# Generated by Django 6.0.3 on 2026-04-05 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('found_items', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='category',
            field=models.CharField(blank=True, choices=[('electronics', 'electronics'), ('cloth', 'cloth'), ('wallet', 'wallet'), ('others', 'others')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='founditem',
            name='image',
            field=models.ImageField(default=1, upload_to='found_items/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='founditem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
