# Generated by Django 6.0.3 on 2026-04-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_items', '0002_lostitem_category_lostitem_image_alter_lostitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostitem',
            name='image',
            field=models.ImageField(upload_to='lost_items/'),
        ),
    ]
