# Generated by Django 6.0.3 on 2026-04-05 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_items', '0003_alter_lostitem_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lostitem',
            name='status',
            field=models.CharField(default='lost', max_length=20),
        ),
        migrations.AlterField(
            model_name='lostitem',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
